version: "3"
services:
  app:
    build: .
    command: python -m flask run --host 0.0.0.0 --port 5000
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/budgetreport
    environment:
      - RDS_USER=$${RDS_USER}
      - RDS_PASSWRD=$${RDS_PASSWRD}
      - RDS_HOST=$${RDS_HOST}
