version: "3"
services:
  app:
    build: .
    command: python -m flask run --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    volumes:
      - .:/var/www/budgetreport
    environment:
      - RDS_USER=${RDS_USER}
      - RDS_PASSWRD=${RDS_PASSWRD}
      - RDS_HOST=${RDS_HOST}
      - FLASK_APP=run.py
      - FLASK_ENV=development
