version: "3"
services:
  test:
    environment:
      - RDS_USER=${RDS_USER}
      - RDS_PASSWRD=${RDS_PASSWRD}
      - RDS_HOST=${RDS_HOST}
    build: .
    command: python -m unittest discover -v
    volumes:
      - .:/var/www/budgetreport

